(() => {
'use strict';

const ENTITY_KINDS=['project','module','class','function','method','parameter','variable','field','type','external'];
const RELATION_KINDS=['contains','imports','inherits','calls','reads','writes','accepts','returns','uses_type','decorated_by'];
const COLORS={project:'#d0a85c',module:'#477d9b',class:'#7060a8',function:'#477c61',method:'#3f7b7b',parameter:'#696b8b',variable:'#686d7a',field:'#8a7350',type:'#9b5368',external:'#596273'};
const SOCKET_COLORS={contains:'#8593a5',imports:'#55a6d9',inherits:'#a88ee8',calls:'#66c49a',reads:'#70b5df',writes:'#df7185',accepts:'#79cfd0',returns:'#e4b96c',uses_type:'#df995c',decorated_by:'#bd8fe2',dependency:'#63a6ca'};
const $=id=>document.getElementById(id);
const els={
 fileInput:$('fileInput'),projectMeta:$('projectMeta'),canvas:$('graphCanvas'),graphPanel:$('graphPanel'),emptyState:$('emptyState'),dropOverlay:$('dropOverlay'),graphStatus:$('graphStatus'),legend:$('legend'),
 projectionButtons:$('projectionButtons'),searchInput:$('searchInput'),searchResults:$('searchResults'),scopeSelect:$('scopeSelect'),depthInput:$('depthInput'),depthOutput:$('depthOutput'),limitInput:$('limitInput'),
 entityFilters:$('entityFilters'),relationFilters:$('relationFilters'),selectAllFilters:$('selectAllFilters'),selectionEmpty:$('selectionEmpty'),selectionDetails:$('selectionDetails'),entityKind:$('entityKind'),entityName:$('entityName'),entityQualified:$('entityQualified'),entityMeta:$('entityMeta'),focusBtn:$('focusBtn'),moduleBtn:$('moduleBtn'),relationList:$('relationList'),relationCountBadge:$('relationCountBadge'),outline:$('outline'),fitBtn:$('fitBtn'),resetBtn:$('resetBtn')
};

const state={graph:null,entityById:new Map(),outgoing:new Map(),incoming:new Map(),children:new Map(),moduleOf:new Map(),projection:'architecture',scope:'overview',depth:1,limit:180,selectedId:null,selectedModuleId:null,entityKinds:new Set(['project','module','class','function','method','field','type','external']),relationKinds:new Set(RELATION_KINDS),viewNodes:[],viewEdges:[],nodeMap:new Map(),camera:{x:0,y:0,scale:1},interaction:null,hoverId:null,dpr:window.devicePixelRatio||1,expandedGroups:new Set(),hierarchyFrames:[]};

function validateGraph(data){if(!data||typeof data!=='object')throw Error('JSON root must be an object.');if(!Array.isArray(data.entities)||!Array.isArray(data.relations))throw Error('Expected entities[] and relations[].');if(!String(data.schema||'').startsWith('pycodegraph/'))throw Error(`Unsupported schema: ${data.schema||'missing'}`);}
function loadGraph(data,label='artifact'){
 validateGraph(data);state.graph=data;state.entityById=new Map(data.entities.map(e=>[e.id,e]));state.outgoing=new Map();state.incoming=new Map();state.children=new Map();state.moduleOf=new Map();
 for(const r of data.relations){pushMap(state.outgoing,r.source,r);pushMap(state.incoming,r.target,r);if(r.kind==='contains')pushMap(state.children,r.source,r.target);}
 for(const e of data.entities)state.moduleOf.set(e.id,findModuleId(e.id));
 const name=data.project?.name||data.entities.find(e=>e.kind==='project')?.name||label;els.projectMeta.textContent=`${name} · ${data.entities.length.toLocaleString()} entities · ${data.relations.length.toLocaleString()} relations · ${data.schema}`;els.emptyState.style.display='none';
 state.selectedId=null;state.selectedModuleId=null;buildFilters();buildOutline();selectProjection('architecture');updateSelectionPanel();
}
function pushMap(map,key,v){if(!map.has(key))map.set(key,[]);map.get(key).push(v);}
function findModuleId(id){let e=state.entityById.get(id),guard=0;while(e&&guard++<60){if(e.kind==='module')return e.id;e=e.parent?state.entityById.get(e.parent):null;}return null;}

function buildFilters(){els.entityFilters.innerHTML='';els.relationFilters.innerHTML='';for(const k of ENTITY_KINDS)els.entityFilters.appendChild(filterCheckbox(k,'entity',state.entityKinds.has(k)));for(const k of RELATION_KINDS)els.relationFilters.appendChild(filterCheckbox(k,'relation',state.relationKinds.has(k)));}
function filterCheckbox(kind,group,checked){const l=document.createElement('label');l.className='filter-item';const cb=document.createElement('input');cb.type='checkbox';cb.checked=checked;cb.addEventListener('change',()=>{const s=group==='entity'?state.entityKinds:state.relationKinds;cb.checked?s.add(kind):s.delete(kind);rebuildProjection();});const t=document.createElement('span');t.textContent=kind;l.append(cb,t);return l;}
function buildOutline(){if(!state.graph)return;els.outline.innerHTML='';for(const m of state.graph.entities.filter(e=>e.kind==='module').sort((a,b)=>(a.qualified_name||'').localeCompare(b.qualified_name||''))){const b=document.createElement('button');b.className='outline-module';b.textContent=m.qualified_name||m.name;b.dataset.id=m.id;b.onclick=()=>{selectNode(m.id);state.selectedModuleId=m.id;state.scope='module';els.scopeSelect.value='module';selectProjection('structure');};els.outline.appendChild(b);}refreshOutlineSelection();}
function refreshOutlineSelection(){els.outline.querySelectorAll('.outline-module').forEach(b=>b.classList.toggle('selected',b.dataset.id===state.selectedModuleId));}
function selectProjection(name){state.projection=name;els.projectionButtons.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.projection===name));if(name==='architecture'){state.scope='overview';els.scopeSelect.value='overview';}if(name==='neighborhood'&&!state.selectedId){const e=state.graph?.entities.find(x=>x.kind==='module')||state.graph?.entities[0];if(e)state.selectedId=e.id;}rebuildProjection();}
function rebuildProjection(){if(!state.graph)return;const p=buildProjection(state.projection);state.viewNodes=p.nodes.map(makeVisualNode);state.viewEdges=p.edges.map((e,i)=>({...e,_key:`${e.source}|${e.target}|${e.kind}|${i}`}));state.nodeMap=new Map(state.viewNodes.map(n=>[n.id,n]));attachPorts();layoutGraph();fitToView();updateLegend();updateStatus();draw();}

function buildProjection(k){if(k==='architecture')return architectureProjection();if(k==='structure')return structureProjection();if(k==='types')return relationProjection(new Set(['class','type','external']),new Set(['inherits','uses_type']));if(k==='calls')return relationProjection(new Set(['class','function','method','external']),new Set(['calls']));if(k==='neighborhood')return neighborhoodProjection();return customProjection();}
function architectureProjection(){const modules=state.graph.entities.filter(e=>e.kind==='module'&&state.entityKinds.has('module'));const ms=new Set(modules.map(e=>e.id)),agg=new Map(),allowed=new Set(['imports','calls','uses_type','inherits']);for(const r of state.graph.relations){if(!allowed.has(r.kind)||!state.relationKinds.has(r.kind))continue;const a=state.moduleOf.get(r.source),b=state.moduleOf.get(r.target);if(!a||!b||a===b||!ms.has(a)||!ms.has(b))continue;const key=a+'\0'+b;let e=agg.get(key)||{source:a,target:b,kind:'dependency',count:0,kinds:{}};e.count++;e.kinds[r.kind]=(e.kinds[r.kind]||0)+1;agg.set(key,e);}return{nodes:modules,edges:[...agg.values()]};}
function structureProjection(){let mid=state.selectedModuleId;if(!mid&&state.selectedId)mid=state.moduleOf.get(state.selectedId);if(!mid)mid=state.graph.entities.find(e=>e.kind==='module')?.id;if(!mid)return{nodes:[],edges:[]};state.selectedModuleId=mid;refreshOutlineSelection();const ids=new Set([mid]),q=[{id:mid,d:0}],max=Math.max(1,state.depth+1);while(q.length&&ids.size<state.limit){const {id,d}=q.shift();if(d>=max)continue;for(const c of state.children.get(id)||[]){const e=state.entityById.get(c);if(!e||!state.entityKinds.has(e.kind)||['parameter','variable'].includes(e.kind))continue;if(!ids.has(c)){ids.add(c);q.push({id:c,d:d+1});if(ids.size>=state.limit)break;}}}const edges=state.graph.relations.filter(r=>r.kind!=='contains'&&state.relationKinds.has(r.kind)&&ids.has(r.source)&&ids.has(r.target));return{nodes:[...ids].map(id=>state.entityById.get(id)).filter(Boolean),edges};}
function relationProjection(kinds,rels){const ak=new Set([...kinds].filter(k=>state.entityKinds.has(k))),ar=new Set([...rels].filter(k=>state.relationKinds.has(k)));let ids=new Set();if(state.scope==='module'&&state.selectedModuleId){for(const e of state.graph.entities)if(state.moduleOf.get(e.id)===state.selectedModuleId&&ak.has(e.kind))ids.add(e.id);}else if(state.scope==='selection'&&state.selectedId)return neighborhoodProjection(ak,ar);else{const degree=new Map();for(const r of state.graph.relations)if(ar.has(r.kind)){const a=state.entityById.get(r.source),b=state.entityById.get(r.target);if(!a||!b||!ak.has(a.kind)||!ak.has(b.kind))continue;degree.set(a.id,(degree.get(a.id)||0)+1);degree.set(b.id,(degree.get(b.id)||0)+1);}[...degree.entries()].sort((a,b)=>b[1]-a[1]).slice(0,state.limit).forEach(([id])=>ids.add(id));}const edges=state.graph.relations.filter(r=>ar.has(r.kind)&&ids.has(r.source)&&ids.has(r.target));return{nodes:[...ids].map(id=>state.entityById.get(id)).filter(Boolean),edges};}
function neighborhoodProjection(kindOverride=null,relOverride=null){if(!state.selectedId)return{nodes:[],edges:[]};const kinds=kindOverride||state.entityKinds,rels=relOverride||state.relationKinds,ids=new Set([state.selectedId]);let front=new Set([state.selectedId]);for(let d=0;d<state.depth&&ids.size<state.limit;d++){const next=new Set();for(const id of front){for(const r of [...(state.outgoing.get(id)||[]),...(state.incoming.get(id)||[])]){if(!rels.has(r.kind))continue;const other=r.source===id?r.target:r.source,e=state.entityById.get(other);if(!e||!kinds.has(e.kind))continue;if(!ids.has(other)){ids.add(other);next.add(other);if(ids.size>=state.limit)break;}}}front=next;if(!front.size)break;}const edges=state.graph.relations.filter(r=>rels.has(r.kind)&&ids.has(r.source)&&ids.has(r.target));return{nodes:[...ids].map(id=>state.entityById.get(id)).filter(Boolean),edges};}
function customProjection(){if(state.scope==='selection'&&state.selectedId)return neighborhoodProjection();let ids=new Set();if(state.scope==='module'&&state.selectedModuleId){for(const e of state.graph.entities)if(state.moduleOf.get(e.id)===state.selectedModuleId&&state.entityKinds.has(e.kind)&&!['parameter','variable'].includes(e.kind))ids.add(e.id);}else{const deg=new Map();for(const r of state.graph.relations)if(state.relationKinds.has(r.kind)){for(const id of [r.source,r.target]){const e=state.entityById.get(id);if(e&&state.entityKinds.has(e.kind)&&!['parameter','variable'].includes(e.kind))deg.set(id,(deg.get(id)||0)+1);}}[...deg.entries()].sort((a,b)=>b[1]-a[1]).slice(0,state.limit).forEach(([id])=>ids.add(id));}const edges=state.graph.relations.filter(r=>state.relationKinds.has(r.kind)&&ids.has(r.source)&&ids.has(r.target));return{nodes:[...ids].map(id=>state.entityById.get(id)).filter(Boolean),edges};}

function makeVisualNode(e){return{...e,x:0,y:0,w:240,h:80,inputPorts:[],outputPorts:[],relationGroups:[],rows:[],portMap:new Map(),_manual:false};}
function intrinsicInputs(n){if(!['function','method'].includes(n.kind))return[];return (state.children.get(n.id)||[]).map(id=>state.entityById.get(id)).filter(e=>e?.kind==='parameter').sort(sourceOrder).map(e=>({key:'param:'+e.id,label:e.name,type:e.attributes?.annotation||'Any',kind:'accepts',entityId:e.id,intrinsic:true,shape:'circle'}));}
function intrinsicOutputs(n){if(!['function','method'].includes(n.kind))return[];const ret=n.attributes?.returns;return[{key:'return',label:'return',type:ret||'Any',kind:'returns',intrinsic:true,shape:'circle'}];}
function sourceOrder(a,b){const A=a.span||{},B=b.span||{};return(A.start_line||0)-(B.start_line||0)||(A.start_col||0)-(B.start_col||0)||(a.name||'').localeCompare(b.name||'');}
function groupKey(id,dir,kind){return `${id}|${dir}|${kind}`;}
function relationLabel(k,dir,count){const incoming=dir==='in';if(k==='dependency')return incoming?`dependencies in · ${count}`:`dependencies out · ${count}`;const base={calls:incoming?'called by':'calls',imports:incoming?'imported by':'imports',inherits:incoming?'base of':'inherits',reads:incoming?'read by':'reads',writes:incoming?'written by':'writes',uses_type:incoming?'used by':'uses type',decorated_by:incoming?'decorates':'decorated by',accepts:incoming?'parameter':'accepts',returns:incoming?'return from':'returns'}[k]||k;return `${base} · ${count}`;}
function relationEndpointId(edge,dir){return dir==='out'?edge.target:edge.source;}
function relationOtherName(edge,dir){const id=relationEndpointId(edge,dir),e=state.entityById.get(id);return e?.name||e?.qualified_name||id;}
function aggregateRelationEndpoints(edges,dir){
 const byId=new Map();
 for(const edge of edges){
  const id=relationEndpointId(edge,dir),entity=state.entityById.get(id);
  let item=byId.get(id);
  if(!item){item={id,entity,name:entity?.name||entity?.qualified_name||id,qualified:entity?.qualified_name||'',count:0,edges:[]};byId.set(id,item);}
  item.count+=edge.count||1;item.edges.push(edge);
 }
 const items=[...byId.values()];
 const nameCounts=new Map();for(const item of items)nameCounts.set(item.name,(nameCounts.get(item.name)||0)+1);
 for(const item of items){const base=nameCounts.get(item.name)>1&&item.qualified?item.qualified:item.name;item.label=item.count>1?`${base} ×${item.count}`:base;}
 return items.sort((a,b)=>a.label.localeCompare(b.label));
}
function endpointPortKey(group,endpointId){return `endpoint:${group.key}:${endpointId}`;}
function attachPorts(){
 const incident=new Map();for(const n of state.viewNodes)incident.set(n.id,{in:new Map(),out:new Map()});
 for(const e of state.viewEdges){const a=incident.get(e.source),b=incident.get(e.target);if(a)pushMap(a.out,e.kind,e);if(b)pushMap(b.in,e.kind,e);}
 for(const n of state.viewNodes){
  n.inputPorts=[];n.outputPorts=[];n.relationGroups=[];n.rows=[];n.portMap=new Map();
  const vins=intrinsicInputs(n),vouts=intrinsicOutputs(n),vr=Math.max(vins.length,vouts.length);
  for(let i=0;i<vr;i++){const row={type:'value',in:vins[i]||null,out:vouts[i]||null};n.rows.push(row);for(const [side,p] of [['in',row.in],['out',row.out]])if(p){p.side=side;p.row=n.rows.length-1;n.portMap.set(p.key,p);(side==='in'?n.inputPorts:n.outputPorts).push(p);}}
  const inc=incident.get(n.id);
  for(const dir of ['in','out'])for(const [kind,edges] of inc[dir]){
    if(kind==='contains')continue;
    if(['function','method'].includes(n.kind)&&((dir==='in'&&kind==='accepts')||(dir==='out'&&kind==='returns')))continue;
    const key=groupKey(n.id,dir,kind),expanded=state.expandedGroups.has(key),g={key,dir,kind,count:edges.reduce((a,e)=>a+(e.count||1),0),edges,expanded,endpointPortById:new Map(),endpointEntries:[]};n.relationGroups.push(g);
  }
  n.relationGroups.sort((a,b)=>a.dir.localeCompare(b.dir)||a.kind.localeCompare(b.kind));
  if(n.relationGroups.length&&n.rows.length)n.rows.push({type:'separator'});
  for(const g of n.relationGroups){
    const gp={key:'group:'+g.key,label:relationLabel(g.kind,g.dir,g.count),kind:g.kind,shape:'diamond',relationGroup:g,side:g.dir,row:n.rows.length};g.port=gp;n.portMap.set(gp.key,gp);(g.dir==='in'?n.inputPorts:n.outputPorts).push(gp);n.rows.push({type:'relation-group',group:g,port:gp});
    if(g.expanded){
      g.endpointEntries=aggregateRelationEndpoints(g.edges,g.dir);
      const shown=g.endpointEntries.slice(0,18);
      for(const entry of shown){const ip={key:endpointPortKey(g,entry.id),label:entry.label,kind:g.kind,shape:'diamond-small',endpointId:entry.id,edges:entry.edges,side:g.dir,row:n.rows.length};g.endpointPortById.set(entry.id,ip);n.portMap.set(ip.key,ip);(g.dir==='in'?n.inputPorts:n.outputPorts).push(ip);n.rows.push({type:'relation-item',group:g,port:ip,endpoint:entry});}
      if(g.endpointEntries.length>shown.length)n.rows.push({type:'more',label:`… ${g.endpointEntries.length-shown.length} more endpoints`});
    }
  }
  if(!n.rows.length)n.rows.push({type:'empty',label:'no exposed interface'});
  n.w=computeNodeWidth(n);n.h=34+n.rows.length*22+10;
 }
 for(const e of state.viewEdges){const s=state.nodeMap.get(e.source),t=state.nodeMap.get(e.target);const sg=s?.relationGroups.find(g=>g.dir==='out'&&g.kind===e.kind),tg=t?.relationGroups.find(g=>g.dir==='in'&&g.kind===e.kind);e.visible=e.kind!=='contains'&&e.kind!=='accepts'&&e.kind!=='returns';e.sourcePort=sg?.expanded?(sg.endpointPortById.get(e.target)||sg.port):sg?.port||null;e.targetPort=tg?.expanded?(tg.endpointPortById.get(e.source)||tg.port):tg?.port||null;}
}
function computeNodeWidth(n){let chars=Math.min(40,Math.max(14,(n.name||'').length));for(const row of n.rows){if(row.type==='value'){for(const p of [row.in,row.out])if(p)chars=Math.max(chars,Math.min(40,(p.label||'').length+(p.type?(' : '+p.type).length:0)));}else if(row.type==='relation-group')chars=Math.max(chars,Math.min(40,row.port.label.length));else if(row.type==='relation-item')chars=Math.max(chars,Math.min(40,row.port.label.length));}return Math.max(210,Math.min(360,95+chars*7));}
function layoutGraph(){if(state.projection==='structure'){layoutStructureGraph();return;}const nodes=state.viewNodes,edges=state.viewEdges;if(!nodes.length)return;const {rank,order}=layeredRanks(nodes,edges);const levels=new Map();for(const n of nodes){const r=rank.get(n.id)||0;pushMap(levels,r,n);}for(const [r,list] of levels)list.sort((a,b)=>(order.get(a.id)||0)-(order.get(b.id)||0));const ranks=[...levels.keys()].sort((a,b)=>a-b);const rankWidths=new Map();for(const r of ranks)rankWidths.set(r,Math.max(...levels.get(r).map(n=>n.w)));let x=0;const xPos=new Map();for(const r of ranks){xPos.set(r,x);x+=rankWidths.get(r)+190;}for(const r of ranks){const list=levels.get(r);let y=0;for(const n of list){n.x=xPos.get(r);n.y=y;y+=n.h+70;}const total=y-70;for(const n of list)n.y-=total/2;}centerLayout(nodes);}
function hierarchyDepthFrom(id,root){let d=0,e=state.entityById.get(id),guard=0;while(e?.parent&&guard++<50){if(e.parent===root)return d+1;e=state.entityById.get(e.parent);d++;}return null;}
function visibleDescendants(rootId){return state.viewNodes.filter(n=>n.id!==rootId&&isDescendantOf(n.id,rootId));}
function layoutStructureGraph(){const nodes=state.viewNodes,edges=state.viewEdges;if(!nodes.length)return;const ids=new Set(nodes.map(n=>n.id)),degree=new Map(nodes.map(n=>[n.id,0]));for(const e of edges){if(ids.has(e.source)&&ids.has(e.target)){degree.set(e.source,(degree.get(e.source)||0)+1);degree.set(e.target,(degree.get(e.target)||0)+1);}}const {rank:semanticRank,order}=layeredRanks(nodes,edges);const rank=new Map();for(const n of nodes){let r=semanticRank.get(n.id)||0;if((degree.get(n.id)||0)===0){let p=n.parent&&state.nodeMap.get(n.parent),guard=0;while(p&&guard++<20){r=Math.max(r,(semanticRank.get(p.id)||rank.get(p.id)||0)+1);p=p.parent&&state.nodeMap.get(p.parent);}}rank.set(n.id,r);}const levels=new Map();for(const n of nodes)pushMap(levels,rank.get(n.id)||0,n);for(const [r,list] of levels){list.sort((a,b)=>{const ap=a.parent||'',bp=b.parent||'';if(ap!==bp)return ap.localeCompare(bp);return(order.get(a.id)||0)-(order.get(b.id)||0)||sourceOrder(a,b);});}const ranks=[...levels.keys()].sort((a,b)=>a-b),rankWidths=new Map();for(const r of ranks)rankWidths.set(r,Math.max(...levels.get(r).map(n=>n.w)));const xPos=new Map();let x=0;for(const r of ranks){xPos.set(r,x);x+=rankWidths.get(r)+230;}const NODE_GAP=86,GROUP_GAP=54;for(const r of ranks){const list=levels.get(r);let y=0,lastParent=null;for(const n of list){const parent=n.parent||'__root__';if(lastParent!==null&&parent!==lastParent)y+=GROUP_GAP;n.x=xPos.get(r);n.y=y;y+=n.h+NODE_GAP;lastParent=parent;}const total=Math.max(0,y-NODE_GAP);for(const n of list)n.y-=total/2;}/* Keep a class and its methods visually close without forcing the whole graph into hierarchy columns. */for(let pass=0;pass<2;pass++){for(const c of nodes.filter(n=>n.kind==='class')){const kids=(state.children.get(c.id)||[]).map(id=>state.nodeMap.get(id)).filter(Boolean);if(!kids.length)continue;const avg=kids.reduce((s,n)=>s+n.y+n.h/2,0)/kids.length;c.y+=(avg-(c.y+c.h/2))*.45;}}centerLayout(nodes);}
function layeredRanks(nodes,edges){const ids=new Set(nodes.map(n=>n.id)),adj=new Map(nodes.map(n=>[n.id,[]]));for(const e of edges)if(ids.has(e.source)&&ids.has(e.target)&&e.source!==e.target)adj.get(e.source).push(e.target);const comps=tarjan(nodes.map(n=>n.id),adj),ci=new Map();comps.forEach((c,i)=>c.forEach(id=>ci.set(id,i)));const dag=comps.map(()=>new Set()),indeg=comps.map(()=>0);for(const [a,outs] of adj)for(const b of outs){const ca=ci.get(a),cb=ci.get(b);if(ca!==cb&&!dag[ca].has(cb)){dag[ca].add(cb);indeg[cb]++;}}const q=[];indeg.forEach((d,i)=>{if(d===0)q.push(i);});const cr=new Array(comps.length).fill(0);while(q.length){const c=q.shift();for(const d of dag[c]){cr[d]=Math.max(cr[d],cr[c]+1);if(--indeg[d]===0)q.push(d);}}const rank=new Map(),order=new Map();comps.forEach((c,i)=>c.forEach((id,j)=>{rank.set(id,cr[i]);order.set(id,j);}));for(let pass=0;pass<5;pass++){const levels=new Map();for(const id of ids)pushMap(levels,rank.get(id)||0,id);const rev=pass%2===1;const rs=[...levels.keys()].sort((a,b)=>rev?b-a:a-b);for(const r of rs){const list=levels.get(r);list.sort((a,b)=>neighborScore(a,rank,order,adj,rev)-neighborScore(b,rank,order,adj,rev));list.forEach((id,i)=>order.set(id,i));}}return{rank,order};}
function neighborScore(id,rank,order,adj,reverse){const vals=[];if(reverse){for(const t of adj.get(id)||[])if((rank.get(t)||0)!==(rank.get(id)||0))vals.push(order.get(t)||0);}else{for(const [s,outs] of adj)if(outs.includes(id)&&(rank.get(s)||0)!==(rank.get(id)||0))vals.push(order.get(s)||0);}if(!vals.length)return order.get(id)||0;return vals.reduce((a,b)=>a+b,0)/vals.length;}
function tarjan(ids,adj){let idx=0;const stack=[],on=new Set(),index=new Map(),low=new Map(),out=[];function visit(v){index.set(v,idx);low.set(v,idx++);stack.push(v);on.add(v);for(const w of adj.get(v)||[]){if(!index.has(w)){visit(w);low.set(v,Math.min(low.get(v),low.get(w)));}else if(on.has(w))low.set(v,Math.min(low.get(v),index.get(w)));}if(low.get(v)===index.get(v)){const c=[];let w;do{w=stack.pop();on.delete(w);c.push(w);}while(w!==v);out.push(c);}}for(const id of ids)if(!index.has(id))visit(id);return out;}
function centerLayout(nodes){let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const n of nodes){minX=Math.min(minX,n.x);maxX=Math.max(maxX,n.x+n.w);minY=Math.min(minY,n.y);maxY=Math.max(maxY,n.y+n.h);}const cx=(minX+maxX)/2,cy=(minY+maxY)/2;for(const n of nodes){n.x-=cx;n.y-=cy;}}

function resizeCanvas(){const r=els.graphPanel.getBoundingClientRect();state.dpr=window.devicePixelRatio||1;els.canvas.width=Math.max(1,Math.floor(r.width*state.dpr));els.canvas.height=Math.max(1,Math.floor(r.height*state.dpr));draw();}
function worldToScreen(x,y){const r=els.graphPanel.getBoundingClientRect();return{x:r.width/2+(x+state.camera.x)*state.camera.scale,y:r.height/2+(y+state.camera.y)*state.camera.scale};}
function screenToWorld(x,y){const r=els.graphPanel.getBoundingClientRect();return{x:(x-r.width/2)/state.camera.scale-state.camera.x,y:(y-r.height/2)/state.camera.scale-state.camera.y};}
function portPos(n,p,side){const row=p?.row??0,y=n.y+34+row*22+11;return{x:side==='in'?n.x:n.x+n.w,y};}
function draw(){const ctx=els.canvas.getContext('2d'),r=els.graphPanel.getBoundingClientRect();ctx.setTransform(state.dpr,0,0,state.dpr,0,0);ctx.clearRect(0,0,r.width,r.height);if(!state.graph)return;drawGrid(ctx,r);drawHierarchyFrames(ctx);drawEdges(ctx);for(const n of state.viewNodes)drawNode(ctx,n);}
function drawGrid(ctx,r){const s=state.camera.scale,step=40*s;if(step<10)return;const ox=(r.width/2+state.camera.x*s)%step,oy=(r.height/2+state.camera.y*s)%step;ctx.strokeStyle='rgba(140,150,160,.055)';ctx.lineWidth=1;ctx.beginPath();for(let x=ox;x<r.width;x+=step){ctx.moveTo(x,0);ctx.lineTo(x,r.height);}for(let y=oy;y<r.height;y+=step){ctx.moveTo(0,y);ctx.lineTo(r.width,y);}ctx.stroke();}
function computeHierarchyFrames(){if(state.projection!=='structure')return[];const frames=[];/* Frames are secondary annotations. The selected module is not wrapped in one giant frame. */const groups=state.viewNodes.filter(n=>n.kind==='class');for(const g of groups){const descendants=state.viewNodes.filter(n=>n.id!==g.id&&isDescendantOf(n.id,g.id));if(!descendants.length)continue;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const n of descendants){minX=Math.min(minX,n.x);minY=Math.min(minY,n.y);maxX=Math.max(maxX,n.x+n.w);maxY=Math.max(maxY,n.y+n.h);}const padX=34,padBottom=36,titleH=28,padTop=48;frames.push({id:g.id,name:g.name,minX:minX-padX,minY:minY-padTop,maxX:maxX+padX,maxY:maxY+padBottom,titleH,descendantIds:descendants.map(n=>n.id)});}frames.sort((a,b)=>(b.maxX-b.minX)*(b.maxY-b.minY)-(a.maxX-a.minX)*(a.maxY-a.minY));return frames;}
function drawHierarchyFrames(ctx){state.hierarchyFrames=computeHierarchyFrames();for(const f of state.hierarchyFrames){const p1=worldToScreen(f.minX,f.minY),p2=worldToScreen(f.maxX,f.maxY),w=p2.x-p1.x,h=p2.y-p1.y;if(w<40||h<30)continue;ctx.fillStyle='rgba(80,90,100,.075)';ctx.strokeStyle='rgba(170,185,200,.28)';ctx.lineWidth=Math.max(1,state.camera.scale);roundRect(ctx,p1.x,p1.y,w,h,8*state.camera.scale);ctx.fill();ctx.stroke();const th=f.titleH*state.camera.scale;ctx.fillStyle='rgba(95,110,125,.18)';roundTopRect(ctx,p1.x,p1.y,w,th,8*state.camera.scale);ctx.fill();if(state.camera.scale>.28){ctx.fillStyle='rgba(225,232,238,.78)';ctx.font=`600 ${Math.max(8,10*state.camera.scale)}px ui-sans-serif,system-ui`;ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(f.name,p1.x+10*state.camera.scale,p1.y+th/2);}}}
function isDescendantOf(id,parent){let e=state.entityById.get(id),guard=0;while(e?.parent&&guard++<50){if(e.parent===parent)return true;e=state.entityById.get(e.parent);}return false;}
function drawEdges(ctx){for(const e of state.viewEdges){if(!e.visible)continue;const a=state.nodeMap.get(e.source),b=state.nodeMap.get(e.target);if(!a||!b||!e.sourcePort||!e.targetPort)continue;const wp1=portPos(a,e.sourcePort,'out'),wp2=portPos(b,e.targetPort,'in'),p1=worldToScreen(wp1.x,wp1.y),p2=worldToScreen(wp2.x,wp2.y),dx=Math.max(55,Math.abs(p2.x-p1.x)*.45);const focused=!!(state.hoverId||state.selectedId),active=e.source===state.hoverId||e.target===state.hoverId||e.source===state.selectedId||e.target===state.selectedId;const dense=state.viewEdges.length>450;ctx.globalAlpha=focused?(active?.88:(dense?.035:.08)):(dense?.10:.34);ctx.strokeStyle=SOCKET_COLORS[e.kind]||'#8794a3';ctx.lineWidth=Math.max(1,Math.min(3,(e.count?1+Math.log2(e.count+1)*.25:1.15)*Math.sqrt(Math.max(.6,state.camera.scale))));ctx.beginPath();ctx.moveTo(p1.x,p1.y);if(p2.x>=p1.x)ctx.bezierCurveTo(p1.x+dx,p1.y,p2.x-dx,p2.y,p2.x,p2.y);else{const bend=Math.max(80,Math.abs(p2.y-p1.y)*.3);ctx.bezierCurveTo(p1.x+dx,p1.y,p1.x+dx,p1.y+bend,(p1.x+p2.x)/2,p1.y+bend);ctx.bezierCurveTo(p2.x-dx,p2.y-bend,p2.x-dx,p2.y,p2.x,p2.y);}ctx.stroke();}ctx.globalAlpha=1;}
function drawNode(ctx,n){const p=worldToScreen(n.x,n.y),w=n.w*state.camera.scale,h=n.h*state.camera.scale;if(w<10||h<8)return;const selected=n.id===state.selectedId,hovered=n.id===state.hoverId;ctx.globalAlpha=state.hoverId&&!hovered&&!selected?.65:1;roundRect(ctx,p.x,p.y,w,h,6*state.camera.scale);ctx.fillStyle='#45484b';ctx.fill();ctx.strokeStyle=selected?'#f0f3f7':hovered?'#bac6d2':'#2a2c2e';ctx.lineWidth=selected?2:1;ctx.stroke();roundTopRect(ctx,p.x,p.y,w,30*state.camera.scale,6*state.camera.scale);ctx.fillStyle=COLORS[n.kind]||'#626b76';ctx.fill();if(state.camera.scale>.28){ctx.fillStyle='#f4f5f6';ctx.font=`600 ${Math.max(8,12*state.camera.scale)}px ui-sans-serif,system-ui`;ctx.textAlign='left';ctx.textBaseline='middle';ctx.fillText(trimText(ctx,n.name,w-20*state.camera.scale),p.x+10*state.camera.scale,p.y+15*state.camera.scale);if(state.camera.scale>.55){ctx.fillStyle='rgba(235,240,244,.72)';ctx.font=`${Math.max(7,9*state.camera.scale)}px ui-monospace,monospace`;ctx.textAlign='right';ctx.fillText(n.kind,p.x+w-8*state.camera.scale,p.y+15*state.camera.scale);}}
 for(let i=0;i<n.rows.length;i++){const row=n.rows[i],y=p.y+(34+i*22+11)*state.camera.scale;if(row.type==='value'){if(row.in)drawValuePort(ctx,row.in,'in',p.x,y,w);if(row.out)drawValuePort(ctx,row.out,'out',p.x,y,w);}else if(row.type==='separator'){ctx.strokeStyle='rgba(255,255,255,.10)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p.x+8*state.camera.scale,y);ctx.lineTo(p.x+w-8*state.camera.scale,y);ctx.stroke();}else if(row.type==='relation-group')drawRelationGroup(ctx,row.group,p.x,y,w);else if(row.type==='relation-item')drawRelationItem(ctx,row.port,row.group,p.x,y,w);else if(row.type==='more'||row.type==='empty'){if(state.camera.scale>.45){ctx.fillStyle='rgba(225,230,235,.48)';ctx.font=`${Math.max(7,9*state.camera.scale)}px ui-sans-serif,system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(row.label||'no exposed interface',p.x+w/2,y);}}}ctx.globalAlpha=1;}
function drawValuePort(ctx,port,side,x,y,w){const s=state.camera.scale,c=port.kind==='returns'?'#e4b96c':'#84cfd2',cx=side==='in'?x:x+w;ctx.fillStyle=c;ctx.strokeStyle='#27292b';ctx.lineWidth=1;ctx.beginPath();ctx.arc(cx,y,Math.max(2.2,4*s),0,Math.PI*2);ctx.fill();ctx.stroke();if(s<.38)return;const type=port.type?` : ${port.type}`:'';ctx.font=`${Math.max(7,10*s)}px ui-sans-serif,system-ui`;ctx.fillStyle='#e0e3e6';ctx.textBaseline='middle';ctx.textAlign=side==='in'?'left':'right';ctx.fillText(trimText(ctx,port.label+type,w*.46),side==='in'?cx+8*s:cx-8*s,y);}
function diamond(ctx,cx,cy,r,color){ctx.fillStyle=color;ctx.strokeStyle='#27292b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cx,cy-r);ctx.lineTo(cx+r,cy);ctx.lineTo(cx,cy+r);ctx.lineTo(cx-r,cy);ctx.closePath();ctx.fill();ctx.stroke();}
function drawRelationGroup(ctx,g,x,y,w){const s=state.camera.scale,c=SOCKET_COLORS[g.kind]||'#9aa5b1',side=g.dir,cx=side==='in'?x:x+w;diamond(ctx,cx,y,Math.max(2.8,4.2*s),c);if(s<.38)return;ctx.font=`600 ${Math.max(7,9.5*s)}px ui-sans-serif,system-ui`;ctx.fillStyle='#cbd2d9';ctx.textBaseline='middle';ctx.textAlign=side==='in'?'left':'right';const chevron=g.expanded?'▾':'▸',txt=`${chevron} ${g.port.label}`;ctx.fillText(trimText(ctx,txt,w*.68),side==='in'?cx+9*s:cx-9*s,y);}
function drawRelationItem(ctx,port,g,x,y,w){const s=state.camera.scale,c=SOCKET_COLORS[g.kind]||'#9aa5b1',side=g.dir,cx=side==='in'?x:x+w;diamond(ctx,cx,y,Math.max(2.2,3.2*s),c);if(s<.42)return;ctx.font=`${Math.max(7,9*s)}px ui-sans-serif,system-ui`;ctx.fillStyle='rgba(230,235,240,.72)';ctx.textBaseline='middle';ctx.textAlign=side==='in'?'left':'right';ctx.fillText(trimText(ctx,port.label,w*.72),side==='in'?cx+8*s:cx-8*s,y);}
function trimText(ctx,text,max){if(ctx.measureText(text).width<=max)return text;let s=text;while(s.length>4&&ctx.measureText(s+'…').width>max)s=s.slice(0,-1);return s+'…';}
function roundRect(ctx,x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();}
function roundTopRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.lineTo(x+w,y+h);ctx.lineTo(x,y+h);ctx.arcTo(x,y,x+r,y,r);ctx.closePath();}
function hitTest(clientX,clientY){const rect=els.canvas.getBoundingClientRect(),w=screenToWorld(clientX-rect.left,clientY-rect.top);for(let i=state.viewNodes.length-1;i>=0;i--){const n=state.viewNodes[i];if(w.x>=n.x&&w.x<=n.x+n.w&&w.y>=n.y&&w.y<=n.y+n.h)return n;}return null;}
function hitHierarchyFrame(clientX,clientY){if(state.projection!=='structure')return null;const rect=els.canvas.getBoundingClientRect(),w=screenToWorld(clientX-rect.left,clientY-rect.top);for(let i=state.hierarchyFrames.length-1;i>=0;i--){const f=state.hierarchyFrames[i];if(w.x>=f.minX&&w.x<=f.maxX&&w.y>=f.minY&&w.y<=f.maxY)return f;}return null;}
function hitRelationGroup(clientX,clientY){const rect=els.canvas.getBoundingClientRect(),w=screenToWorld(clientX-rect.left,clientY-rect.top);for(let i=state.viewNodes.length-1;i>=0;i--){const n=state.viewNodes[i];if(w.x<n.x||w.x>n.x+n.w||w.y<n.y+34||w.y>n.y+n.h)continue;const row=Math.floor((w.y-(n.y+34))/22),r=n.rows[row];if(r?.type==='relation-group')return r.group;}return null;}
function toggleRelationGroup(g){if(state.expandedGroups.has(g.key))state.expandedGroups.delete(g.key);else state.expandedGroups.add(g.key);const manual=new Map(state.viewNodes.filter(n=>n._manual).map(n=>[n.id,{x:n.x,y:n.y}]));const p=buildProjection(state.projection);state.viewNodes=p.nodes.map(makeVisualNode);state.viewEdges=p.edges.map((e,i)=>({...e,_key:`${e.source}|${e.target}|${e.kind}|${i}`}));state.nodeMap=new Map(state.viewNodes.map(n=>[n.id,n]));attachPorts();layoutGraph();for(const [id,pos] of manual){const n=state.nodeMap.get(id);if(n){n.x=pos.x;n.y=pos.y;n._manual=true;}}updateLegend();updateStatus();draw();}
function fitToView(){if(!state.viewNodes.length){state.camera={x:0,y:0,scale:1};draw();return;}let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const n of state.viewNodes){minX=Math.min(minX,n.x);maxX=Math.max(maxX,n.x+n.w);minY=Math.min(minY,n.y);maxY=Math.max(maxY,n.y+n.h);}const r=els.graphPanel.getBoundingClientRect(),w=Math.max(100,maxX-minX+100),h=Math.max(100,maxY-minY+100);state.camera.scale=Math.max(.07,Math.min(1.35,Math.min(r.width/w,r.height/h)*.94));state.camera.x=-(minX+maxX)/2;state.camera.y=-(minY+maxY)/2;draw();}

function selectNode(id){if(!id||!state.entityById.has(id))return;state.selectedId=id;const m=state.moduleOf.get(id);if(m)state.selectedModuleId=m;updateSelectionPanel();refreshOutlineSelection();draw();}
function updateSelectionPanel(){const e=state.selectedId?state.entityById.get(state.selectedId):null;els.selectionEmpty.hidden=!!e;els.selectionDetails.hidden=!e;if(!e){els.relationList.textContent='No selection.';els.relationCountBadge.textContent='0';return;}els.entityKind.textContent=e.kind;els.entityKind.style.borderColor=COLORS[e.kind]||'#678';els.entityName.textContent=e.name;els.entityQualified.textContent=e.qualified_name||e.id;const rows=[];if(e.span)rows.push(['file',e.span.path||''],['lines',`${e.span.start_line??'?'}–${e.span.end_line??'?'}`]);if(e.parent)rows.push(['parent',state.entityById.get(e.parent)?.qualified_name||e.parent]);for(const[k,v]of Object.entries(e.attributes||{}))rows.push([k,typeof v==='object'?JSON.stringify(v):String(v)]);els.entityMeta.innerHTML=rows.map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');const rs=[...(state.outgoing.get(e.id)||[]).map(r=>({...r,dir:'out'})),...(state.incoming.get(e.id)||[]).map(r=>({...r,dir:'in'}))];els.relationCountBadge.textContent=rs.length.toLocaleString();els.relationList.innerHTML=rs.slice(0,250).map(r=>{const oid=r.dir==='out'?r.target:r.source,o=state.entityById.get(oid);return`<div class="relation-row" data-id="${attr(oid)}"><span class="relation-kind">${r.dir==='out'?'→':'←'} ${esc(r.kind)}</span><span class="relation-target">${esc(o?.qualified_name||oid)}</span></div>`;}).join('')||'<span class="muted">No relations.</span>';els.relationList.querySelectorAll('.relation-row').forEach(row=>row.onclick=()=>selectNode(row.dataset.id));}
function updateLegend(){const visible=[...new Set(state.viewEdges.filter(e=>e.visible).map(e=>e.kind))];els.legend.innerHTML=`<span class="legend-item"><span class="legend-socket value"></span>value socket</span><span class="legend-item"><span class="legend-diamond"></span>relation port (expand for endpoint names)</span><span class="legend-item">▣ class frame (does not control auto-layout)</span>`+(visible.length?visible.map(k=>`<span class="legend-item"><span class="legend-socket" style="background:${SOCKET_COLORS[k]||'#899'}"></span>${esc(k)}</span>`).join(''):'');}
function updateStatus(){const shown=state.viewEdges.filter(e=>e.visible).length;els.graphStatus.textContent=`${state.projection} · ${state.viewNodes.length.toLocaleString()} nodes · ${shown.toLocaleString()} links · ${state.projection==='structure'?'drag a class frame to move that class group · ':''}select/hover a node to focus · expand ◇ to name endpoints`;}
function performSearch(q){if(!state.graph||!q.trim()){els.searchResults.innerHTML='';return;}const t=q.trim().toLowerCase(),rs=state.graph.entities.filter(e=>(e.name||'').toLowerCase().includes(t)||(e.qualified_name||'').toLowerCase().includes(t)).slice(0,30);els.searchResults.innerHTML=rs.map(e=>`<div class="search-item" data-id="${attr(e.id)}"><div class="name">${esc(e.name)} <span class="pill">${esc(e.kind)}</span></div><div class="qualified">${esc(e.qualified_name||'')}</div></div>`).join('');els.searchResults.querySelectorAll('.search-item').forEach(row=>row.onclick=()=>{selectNode(row.dataset.id);state.scope='selection';els.scopeSelect.value='selection';selectProjection('neighborhood');els.searchResults.innerHTML='';});}
function openFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{loadGraph(JSON.parse(r.result),file.name);}catch(e){alert(`Could not load CodeGraph JSON:\n${e.message}`);}};r.onerror=()=>alert('Could not read file.');r.readAsText(file);}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}function attr(v){return esc(v).replace(/`/g,'&#96;');}

els.fileInput.onchange=e=>openFile(e.target.files?.[0]);els.projectionButtons.onclick=e=>{const b=e.target.closest('button[data-projection]');if(b&&state.graph)selectProjection(b.dataset.projection);};els.searchInput.oninput=e=>performSearch(e.target.value);els.depthInput.oninput=e=>{state.depth=Number(e.target.value);els.depthOutput.value=state.depth;rebuildProjection();};els.limitInput.value=state.limit;els.limitInput.onchange=e=>{state.limit=Math.max(20,Math.min(800,Number(e.target.value)||180));e.target.value=state.limit;rebuildProjection();};els.scopeSelect.onchange=e=>{state.scope=e.target.value;rebuildProjection();};els.selectAllFilters.onclick=()=>{state.entityKinds=new Set(ENTITY_KINDS);state.relationKinds=new Set(RELATION_KINDS);buildFilters();rebuildProjection();};els.focusBtn.onclick=()=>{state.scope='selection';els.scopeSelect.value='selection';selectProjection('neighborhood');};els.moduleBtn.onclick=()=>{if(!state.selectedId)return;state.selectedModuleId=state.moduleOf.get(state.selectedId);if(state.selectedModuleId){state.scope='module';els.scopeSelect.value='module';selectProjection('structure');}};els.fitBtn.onclick=fitToView;els.resetBtn.onclick=()=>{state.expandedGroups.clear();state.selectedId=null;state.selectedModuleId=null;state.scope='overview';els.scopeSelect.value='overview';selectProjection('architecture');updateSelectionPanel();};

els.canvas.addEventListener('mousedown',e=>{const g=hitRelationGroup(e.clientX,e.clientY);if(g&&e.button===0){toggleRelationGroup(g);return;}const n=hitTest(e.clientX,e.clientY);if(n&&e.button===0){const r=els.canvas.getBoundingClientRect(),w=screenToWorld(e.clientX-r.left,e.clientY-r.top);state.interaction={kind:'node',id:n.id,dx:w.x-n.x,dy:w.y-n.y,startX:e.clientX,startY:e.clientY};selectNode(n.id);els.canvas.classList.add('dragging-node');return;}const f=hitHierarchyFrame(e.clientX,e.clientY);if(f&&e.button===0){const ids=[f.id,...f.descendantIds].filter(id=>state.nodeMap.has(id)),start=new Map(ids.map(id=>{const q=state.nodeMap.get(id);return[id,{x:q.x,y:q.y}];}));state.interaction={kind:'frame',frameId:f.id,startX:e.clientX,startY:e.clientY,start};selectNode(f.id);els.canvas.classList.add('dragging-node');return;}state.interaction={kind:'pan',startX:e.clientX,startY:e.clientY,cx:state.camera.x,cy:state.camera.y};els.canvas.classList.add('dragging');});
window.addEventListener('mousemove',e=>{if(state.interaction?.kind==='node'){const r=els.canvas.getBoundingClientRect(),w=screenToWorld(e.clientX-r.left,e.clientY-r.top),n=state.nodeMap.get(state.interaction.id);if(n){n.x=w.x-state.interaction.dx;n.y=w.y-state.interaction.dy;n._manual=true;draw();}return;}if(state.interaction?.kind==='frame'){const dx=(e.clientX-state.interaction.startX)/state.camera.scale,dy=(e.clientY-state.interaction.startY)/state.camera.scale;for(const[id,pos]of state.interaction.start){const n=state.nodeMap.get(id);if(n){n.x=pos.x+dx;n.y=pos.y+dy;n._manual=true;}}draw();return;}if(state.interaction?.kind==='pan'){state.camera.x=state.interaction.cx+(e.clientX-state.interaction.startX)/state.camera.scale;state.camera.y=state.interaction.cy+(e.clientY-state.interaction.startY)/state.camera.scale;draw();return;}const n=hitTest(e.clientX,e.clientY),id=n?.id||null;if(id!==state.hoverId){state.hoverId=id;draw();}});
window.addEventListener('mouseup',()=>{state.interaction=null;els.canvas.classList.remove('dragging','dragging-node');});
els.canvas.addEventListener('wheel',e=>{e.preventDefault();const r=els.canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top,before=screenToWorld(sx,sy),f=Math.exp(-e.deltaY*.001);state.camera.scale=Math.max(.05,Math.min(3,state.camera.scale*f));const after=screenToWorld(sx,sy);state.camera.x+=after.x-before.x;state.camera.y+=after.y-before.y;draw();},{passive:false});
els.canvas.addEventListener('dblclick',e=>{const n=hitTest(e.clientX,e.clientY);if(!n)return;selectNode(n.id);if(['module','class'].includes(n.kind)){state.selectedModuleId=state.moduleOf.get(n.id)||n.id;state.scope='module';els.scopeSelect.value='module';selectProjection('structure');}else{state.scope='selection';els.scopeSelect.value='selection';selectProjection('neighborhood');}});
['dragenter','dragover'].forEach(t=>window.addEventListener(t,e=>{e.preventDefault();els.dropOverlay.classList.add('visible');}));['dragleave','drop'].forEach(t=>window.addEventListener(t,e=>{e.preventDefault();if(t==='drop'){els.dropOverlay.classList.remove('visible');openFile(e.dataTransfer.files?.[0]);}else if(e.target===document.documentElement||e.target===document.body)els.dropOverlay.classList.remove('visible');}));window.addEventListener('resize',resizeCanvas);resizeCanvas();buildFilters();
})();
